version: '3.8'
services:
  py4web:
    build:
      dockerfile_inline: |
        FROM python:3.12-slim
        WORKDIR /apps
        COPY apps /apps
        RUN pip install -U py4web
        CMD ["py4web", "run", "/apps", "--host", "127.0.0.1", "--port", "8000"]
    network_mode: pasta
    ports:
    - "127.0.0.1:8000:8000"